# Generated by Django 3.2.5 on 2021-07-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='sessionize_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='SessionizeにおけるプロポーザルID'),
        ),
    ]
