# Generated by Django 3.2.5 on 2021-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_proposal_sessionize_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='track',
            field=models.CharField(choices=[('Python core and around', 'Python core and around'), ('Machine learning', 'Machine learning'), ('Web programming', 'Web programming'), ('Visual / Game / Music', 'Visual / Game / Music'), ('Outside of Python language', 'Outside of Python language'), ('Approaching to social problem', 'Approaching to social problem'), ('Only for fun or try new technique', 'Only for fun or try new technique'), ('Anything else basically which doesn’t fall into the types of topics above', 'Anything else basically which doesn’t fall into the types of topics above')], max_length=73, verbose_name='セッションのカテゴリ'),
        ),
    ]
